### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by shatl** [mj1856/DotNetOpenAuth.GoogleOAuth2#13]
Hi Matt,
could you please provide sample web application? 

From the documentation is is not clear where to put following code
```
// add this line
GoogleOAuth2Client.RewriteRequest();

// it belongs right before your existing call to
OAuthWebSecurity.VerifyAuthentication(....)
```

**Comment by mj1856** [comment]
This was made a few years ago, for use with the MVC4 starter templates that ship with VS2012.  It does not apply to the current MVC5 or the next MVC6.   Sorry, but I have no interest in supporting it with further examples.
